# Generated by Django 3.1.4 on 2020-12-15 05:52

import django.core.validators
from django.db import migrations, models
import olms.models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0005_counts_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counts',
            name='month',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=olms.models.rename_and_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'img'])]),
        ),
    ]
