# Generated by Django 3.1.4 on 2020-12-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0009_auto_20201226_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('ct_granted', 'CT granted'), ('granted', 'granted'), ('ct_rejected', 'CT rejected'), ('rejected', 'rejected'), ('on_leave', 'On Leave'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='outing',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('ct_granted', 'CT granted'), ('granted', 'granted'), ('ct_rejected', 'CT rejected'), ('rejected', 'rejected'), ('on_outing', 'On Outing'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=11),
        ),
    ]
