# Generated by Django 3.1.4 on 2021-01-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0011_userprofile_classs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counts',
            name='month',
            field=models.IntegerField(default=1),
        ),
    ]
