# Generated by Django 3.1.4 on 2020-12-29 17:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('olms', '0011_userprofile_classs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hod', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('puc', 'PUC'), ('cse', 'CSE'), ('mech', 'MECH'), ('chem', 'CHEM'), ('ece', 'ECE'), ('mme', 'MME'), ('civil', 'CIVIL')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2020, 12, 29))),
                ('branch', models.CharField(choices=[('puc', 'PUC'), ('cse', 'CSE'), ('mech', 'MECH'), ('chem', 'CHEM'), ('ece', 'ECE'), ('mme', 'MME'), ('civil', 'CIVIL')], max_length=5)),
                ('subjects', models.CharField(max_length=1000)),
                ('lecturers', models.CharField(max_length=1000)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HOD', to='oams.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_time', models.DateTimeField(default=datetime.datetime(2020, 12, 29, 17, 14, 45, 216904, tzinfo=utc))),
                ('attended', models.BooleanField(default=False)),
                ('classs', models.CharField(max_length=3)),
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='oams.lecturer')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='olms.userprofile')),
            ],
        ),
    ]
