# Generated by Django 3.1.4 on 2020-12-29 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='classs',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='lecture_time',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='lecturer',
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_time', models.DateTimeField(default=datetime.datetime(2020, 12, 29, 17, 21, 5, 303294, tzinfo=utc))),
                ('classs', models.CharField(max_length=3)),
                ('lecturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='oams.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='attendence',
            name='lecture',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='oams.lecture'),
        ),
    ]
