# Generated by Django 3.1.4 on 2020-12-29 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oams', '0002_auto_20201229_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_duration',
            field=models.DurationField(default=None),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 17, 49, 59, 768087, tzinfo=utc)),
        ),
    ]
