# Generated by Django 3.1.4 on 2020-12-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oams', '0003_auto_20201229_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
