# Generated by Django 3.1.4 on 2020-12-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oams', '0004_auto_20201229_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='oams.lecturer'),
        ),
    ]
