# Generated by Django 3.1.4 on 2020-12-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olms', '0011_userprofile_classs'),
        ('oams', '0005_auto_20201229_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='lecture',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='oams.lecture'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='olms.userprofile'),
        ),
    ]
