# Generated by Django 3.1.4 on 2021-01-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oams', '0008_lecturer_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ImageField(blank=True, default=None, null=True, upload_to='tempfaces/')),
            ],
        ),
    ]
